### ISSUE TITLE
Endless blood droplets

### ISSUE THREAD

**Issue by lord-andre** [pa1nki113r/Project_Brutality#294]
Kill a Hellknight, Baron of hell or cyberdemon with, for example, the quadruple shotgun. After their death, drops of blood spawn again and again. With the appropriate sound.
Apparently, the hit zone is crucial. This occurs with the baron when he is hit in the torso area. With the Hellknigh, it happens when you hit the leg area. 

~~Unfortunately, I can't upload pictures right now. I'll try to send the pictures later.~~
Okay, I couldn't do it with Firefox. With Microsoft Edge I can upload pictures? Weird...

Hellknight:
![hellknight_splatter3](https://user-images.githubusercontent.com/54155260/71315989-f858f680-2468-11ea-9543-bc0418136146.gif)

Cyberdemon:
![cyber_blood2](https://user-images.githubusercontent.com/54155260/71316061-212dbb80-246a-11ea-875c-d0849e695dca.gif)

Map view with "IDDT":
![triangles3](https://user-images.githubusercontent.com/54155260/71316085-97cab900-246a-11ea-8a59-e14ef11b7f6e.gif)

The individual drops of blood are represented as the Doomguy figure. See picture:
![doomguy_droplet](https://user-images.githubusercontent.com/54155260/71316137-728a7a80-246b-11ea-8b94-ad1626121eed.png)

**Comment by pa1nki113r** [comment]
Spent a good awhile tonight fixing these issues, can happily report I've fixed the problem on my end.

**Comment by lord-andre** [comment]
The blood problem no longer occur for the Baron and Hellknight, thank you.
For the Cyberdemon it seems unchanged, he still bubbles blood.

New:
Headshot a ShotgunGuy with the quad_ssg.
Sometimes the giblet "gib_newsergeantuppertorso" or "...LOWERtorso" appear. Then there also occurs the endless blood problem.

**Comment by scaryred24** [comment]
Has this been looked into yet? I'd rather that this oversight gets corrected before closing this thread.

**Comment by lord-andre** [comment]
As of today, January 17th, 2020, version number (commit) 6a649ee, the problem persists.

**Comment by lord-andre** [comment]
Here are a few more enemies who also have the blood problem:

Flying Arachnotron ("Arachnophyte"):
 -gun and leg remains.

Mancubus:
Remains from killing by rocket launcher.

Hellknight remains: "gib_hellknightarm"
After these pieces were shot further, a pool of blood remains.

**Comment by CaptPatrick01** [comment]
![Screenshot_Doom_20200306_143730](https://user-images.githubusercontent.com/29268823/76128185-7896ee80-5fb8-11ea-9773-486c5cc7eb74.png)
![Screenshot_Doom_20200306_143739](https://user-images.githubusercontent.com/29268823/76128195-7e8ccf80-5fb8-11ea-8f51-24d4e6511553.png)
![Screenshot_Doom_20200306_143811](https://user-images.githubusercontent.com/29268823/76128199-8187c000-5fb8-11ea-8d64-8384e6b30ac7.png)

I have Identified some gibs that are constantly spewing droplets, probably came from arachnotron variants. Likely the aforementioned Arachnophyte. At least unlike the Hell Knight, these ones aren't deafening.

**Comment by pa1nki113r** [comment]
Fixed as of 4/19/20
