### ISSUE TITLE
LMG ADS not hiding crosshair

### ISSUE THREAD

**Issue by sebastianpanetta** [pa1nki113r/Project_Brutality#776]
With the new update, LMG does not toggle crosshair when ADS

**Comment by JMartinez9820** [comment]
Fixed in my branch and pull request

**Comment by JMartinez9820** [comment]
https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch

**Comment by sebastianpanetta** [comment]
Thank you very much as always, cloning right now!

**Comment by sebastianpanetta** [comment]
@JMartinez9820 tested your branch and issue still persists :(

**Comment by JMartinez9820** [comment]
I'll fix it later. I'm not home at the moment.

**Comment by sebastianpanetta** [comment]
Sure, no problem! Thank you very much

**Comment by JMartinez9820** [comment]
> Sure, no problem! Thank you very much

https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch
@sebastianpanetta  Now fixed

**Comment by sebastianpanetta** [comment]
Yep, cloned your branch and it works flawlessly, thank you very much
