### ISSUE TITLE
Mini-gun sounds disappears

### ISSUE THREAD

**Issue by Nightmarekiller84** [pa1nki113r/Project_Brutality#798]
The alt-fire of the Minigun in which is rotating the barrels in any mod/state of the weapon, disappears if you ledge-grab

**Comment by JMartinez9820** [comment]
Fixed in the latest commit. Redownload again if necessary.

**Comment by Nightmarekiller84** [comment]
OK, thanks !!

Out of curiosity, where you comment for weapons changes or suggestions ?

**Comment by JMartinez9820** [comment]
@Nightmarekiller84  In the PB Discord server. This issue can now be closed. If you need a link to the server here it is: https://discord.gg/2hJxXPc

**Comment by Nightmarekiller84** [comment]
Thanks for all your help !!

**Comment by Nightmarekiller84** [comment]
Errrrrr, I just downloaded the latest one from discord(the one you posted) and the minigun sounds bug still persists. To be more accurate is the UPGRADED Minigun that has sound issues. Unless of course it is planned for later.

Thanks for the fix with the Revolver and Deagle.

**Comment by JMartinez9820** [comment]
Damn... I'm so sorry about. Looks like I forgot something like a dumbass. I was such in a rush to fix it, but I'll fix the upgraded Minigun as soon as I can today.

**Comment by Nightmarekiller84** [comment]
Jesus dude, I am not such an a**hole to complain to the people who working their free time to satisfy us you know LOL.
Take it easy LOL.
All the best and take your time, no need to do things instantly.

**Comment by JMartinez9820** [comment]
And fixed

**Comment by Nightmarekiller84** [comment]
That was way too fast............................Thanks LOL
